CREATE TABLE IF NOT EXISTS MEMORY_FRAGMENTS (
    FRAGMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TOKENS INTEGER NOT NULL,
    REQUEST_MESSAGE_JSON TEXT NOT NULL,
    RESPONSE_MESSAGE_JSON TEXT NOT NULL,
    CREATED_AT INTEGER NOT NULL,
    UPDATED_AT INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS UPLOAD_ENTRIES (
   ENTRY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   UNIQUE_KEY TEXT NOT NULL UNIQUE,
   MODEL TEXT NOT NULL,
   LENGTH INTEGER NOT NULL,
   FILENAME TEXT NOT NULL,
   UPLOAD_ID TEXT NULL,
   UPLOADED TEXT NOT NULL,
   EXPIRES_AT INTEGER NULL,
   CREATED_AT INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS KNOWLEDGE_DOCUMENTS (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    RESOURCE TEXT NOT NULL UNIQUE,
    RESOURCE_MIME TEXT NOT NULL,
    RESOURCE_LENGTH INTEGER NOT NULL,
    RESOURCE_LAST_UPDATED_AT INTEGER NOT NULL,
    RESOURCE_CONTENT TEXT NOT NULL,
    CREATED_AT INTEGER NOT NULL
);

CREATE VIRTUAL TABLE IF NOT EXISTS KNOWLEDGE_SEGMENTS USING VEC0 (
    SEGMENT_ID INTEGER PRIMARY KEY,
    DOCUMENT_ID INTEGER NOT NULL,
    POSITION INTEGER NOT NULL,
    LENGTH INTEGER NOT NULL,
    VECTOR FLOAT[1024],
    CREATED_AT INTEGER NOT NULL
);