CREATE TABLE IF NOT EXISTS MEMORY_FRAGMENTS (
    FRAGMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TOKENS INTEGER NOT NULL,
    REQUEST_MESSAGE_JSON TEXT NOT NULL,
    RESPONSE_MESSAGE_JSON TEXT NOT NULL,
    CREATED_AT INTEGER NOT NULL,
    UPDATED_AT INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS UPLOAD_ENTRIES (
   ENTRY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   UNIQUE_KEY TEXT NOT NULL UNIQUE,
   MODEL TEXT NOT NULL,
   LENGTH INTEGER NOT NULL,
   FILENAME TEXT NOT NULL,
   UPLOAD_ID TEXT NULL,
   UPLOADED TEXT NOT NULL,
   EXPIRES_AT INTEGER NULL,
   CREATED_AT INTEGER NOT NULL
);