spring:
  datasource:
    url: jdbc:sqlite:./data/moss.db?enable_load_extension=true
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-init-sql: SELECT load_extension('${SQLITE_VEC_LIB}');

  sql:
    init:
      mode: always
      schema-locations: classpath:infra/sql/schema.sql

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:infra/mapper/*.xml
  type-handlers-package: io.github.oldmanpushcart.moss.infra.ibatis.type

moss:
  infra:
    memory:
      max-tokens: 100000
      max-count: 1000
      duration: 1h
    downloader:
      location: ./data/downloads
    uploader:
      oss-expires-duration: 48h
      clean-cron-express: 0 */5 * * * ?
      clean-batch-size: 100
      clean-queue-capacity: 1000
    dashscope:
      api-key: ${DASHSCOPE_AK}
      http:
        connect-timeout: 30s
        read-timeout: 30s
        write-timeout: 30s
        ping-interval: 10s