spring:

  datasource:
    url: jdbc:sqlite:./data/moss.db?enable_load_extension=true&journal_mode=WAL
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-init-sql: SELECT load_extension('${SQLITE_VEC_LIB}');

  sql:
    init:
      mode: always
      schema-locations: classpath:backend/sql/schema.sql

  config:
    import: file:./cfg/moss.yml

logging:
  config: file:./cfg/logback.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath:backend/mapper/*.xml
  type-handlers-package: io.github.oldmanpushcart.moss.backend.ibatis.type