spring:

  datasource:
    url: jdbc:sqlite:./data/moss.db
    driver-class-name: org.sqlite.JDBC

  #  这个配置是留给RAG使用，暂不开启
  #  datasource:
  #    url: jdbc:sqlite:./data/moss.db?enable_load_extension=true
  #    driver-class-name: org.sqlite.JDBC
  #    hikari:
  #      connection-init-sql: SELECT load_extension('${SQLITE_VEC_LIB}');

  sql:
    init:
      mode: always
      schema-locations: classpath:infra/sql/schema.sql

  config:
    import: file:./cfg/moss.yml

logging:
  config: file:./cfg/logback.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:infra/mapper/*.xml
  type-handlers-package: io.github.oldmanpushcart.moss.infra.ibatis.type