CREATE TABLE IF NOT EXISTS MEMORY_FRAGMENTS (
    FRAGMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UUID TEXT NOT NULL,
    TOKENS INTEGER NOT NULL,
    REQUEST_MESSAGE_JSON TEXT NOT NULL,
    RESPONSE_MESSAGE_JSON TEXT NOT NULL,
    CREATED_AT INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS UPLOAD_ENTRIES (
   ENTRY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   MODEL TEXT NOT NULL,
   MIME TEXT NOT NULL,
   LENGTH INTEGER NOT NULL,
   SOURCE TEXT NOT NULL,
   UPLOAD TEXT NULL,
   UPLOAD_KEY TEXT NULL UNIQUE,
   STATUS INTEGER NOT NULL,
   EXPIRES_AT INTEGER NULL,
   CREATED_AT INTEGER NOT NULL,
   UPDATED_AT INTEGER NOT NULL,
   VERSION INTEGER NOT NULL
);